---
- name: Configure aliases
  template: src=files/alias.tpl dest=~/.bash_aliases

- name: Install aptitude
  become: "yes"
  apt: pkg=aptitude state=present update_cache=yes cache_valid_time=3600

- name: Update apt cache
  become: "yes"
  apt:
    update_cache: yes
    cache_valid_time: 3600

- name: Upgrade apt packages
  become: "yes"
  apt:
    upgrade: "safe"
  
- name: "Install base packages"
  become: "yes"
  apt:
    name: "{{item}}"
    state: present
  with_items:
    - libboost-all-dev
    - git-core
    - tar
    - unzip
    - wget
    - bzip2
    - build-essential
    - autoconf
    - libtool
    - libxml2-dev
    - libgeos-dev
    - libgeos++-dev
    - libpq-dev
    - libbz2-dev
    - libproj-dev
    - munin-node
    - munin
    - libprotobuf-c0-dev
    - protobuf-c-compiler
    - libfreetype6-dev
    - libpng12-dev
    - libtiff5-dev
    - libicu-dev
    - libgdal-dev
    - libcairo-dev
    - libcairomm-1.0-dev
    - libagg-dev
    - liblua5.2-dev
    - ttf-unifont
    - lua5.1
    - liblua5.1-dev
    - libgeotiff-epsg
    - htop
