---
- name: Configure aliases
  template: src=files/alias.tpl dest=~/.bash_aliases

- name: Install aptitude
  become: "yes"
  apt: pkg=aptitude state=present update_cache=yes cache_valid_time=3600

- name: Update apt cache
  become: "yes"
  apt:
    update_cache: yes
    cache_valid_time: 3600

- name: Upgrade apt packages
  become: "yes"
  apt:
    upgrade: "safe"
  
- name: "Install base packages"
  become: "yes"
  apt:
    name: "{{item}}"
    state: present
  with_items:
    - curl
    - unzip
    - gdal-bin
    - tar
    - wget
    - bzip2
    - build-essential
    - clang
    - git
