---
- name: "Install imposm3 packages"
  become: "yes"
  apt:
    name: "{{item}}"
    state: present
  with_items:
    - libleveldb-dev
    - libgeos-dev
    - golang-gogoprotobuf-dev

- name: "Copy imposm3 binary file to /usr/local/bin/"
  become: "yes"
  copy:
    src: files/imposm3-0.5.0
    dest: /usr/local/bin/imposm3
    mode: 0755

- name: Create imposm3 folder
  file:
    path: ~/src/imposm3
    state: directory

- name: "Copy imposm3 default mapping to ~/src/imposm3/default-mapping.json"
  copy:
    src: files/default-mapping.json
    dest: ~/src/imposm3/default-mapping.json
    mode: 0755
