---
- name: "Include vars"
  include_vars: "database.yaml"

- name: "Install postgresql packages"
  become: "yes"
  apt:
    name: "{{item}}"
    state: present
  with_items:
    - postgresql
    - postgresql-contrib
    - postgis
    - postgresql-9.5-postgis-2.2
    - python-psycopg2

- name: "Create database osm"
  become: "yes"
  become_user: "postgres"
  postgresql_db:
    name: "{{osm_database}}"
  when: osm_database is defined and osm_database != ""

- name: "Create user renderosm"
  become: "yes"
  become_user: "postgres"
  postgresql_user:
    db: "{{osm_database}}"
    name: "{{osm_user_name}}"
    password: "{{osm_user_password}}"
    priv: "ALL"
    state: present
  when: osm_database is defined and osm_database != "" and osm_user_name is defined and osm_user_name != "" and osm_user_password is defined and osm_user_password != ""

- name: "Create extension postgis to database osm"
  become: "yes"
  become_user: "postgres"
  postgresql_ext:
    name: postgis
    db: "{{osm_database}}"
  when: osm_database is defined and osm_database != ""

- name: "Create extension hstore to database osm"
  become: "yes"
  become_user: "postgres"
  postgresql_ext:
    name: hstore
    db: "{{osm_database}}"
  when: osm_database is defined and osm_database != ""

- name: "Create OS user {{osm_user_name}}"
  become: "yes"
  user:
    name: "{{osm_user_name}}"
    password: "{{osm_user_password_sha512}}"
    comment: "Creates OS postgresql OSM User"
