---
- name: "Install mapnik packages"
  become: "yes"
  apt:
    name: "{{item}}"
    state: present
  with_items:
    - autoconf
    - apache2-dev
    - libtool
    - libxml2-dev
    - libbz2-dev
    - libgeos-dev
    - libgeos++-dev
    - libproj-dev
    - gdal-bin
    - libgdal1-dev
    - libmapnik-dev
    - mapnik-utils
    - python-mapnik
